version: '3.8'
services:
  BACKEND:
    image: lasregistry/devops
    volumes:
      - ./app:/app
      - .m2:/root/.m2
    ports:
      - 8089:8089
    depends_on:
      - MYSQL-DATABASE
  MYSQL-DATABASE:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: root
      MYSQL_PASSWORD: root

    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql
  FRONTEND:
    image: ghaith19/frontendapp
    volumes:
      - ./app:/app
    ports:
      - 80:80
    depends_on:
      - BACKEND
